# Generated by Django 5.0.1 on 2024-02-02 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_position_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.category'),
        ),
    ]
